### ISSUE TITLE
Provide separate MFA attributes for resolver and validation

### ISSUE THREAD

**Issue by mmoayyed** [Unicon/cas-mfa#103]
The MFA attribute that is specified in the configuration indicates both the attribute that should be retrieved for the user to indicate MFA, AND the attribute that is going to be produced in the CAS assertion. 

Separate them.

**Comment by dima767** [comment]
Should this be targeting an RC2 as RC1 is already released?

**Comment by mmoayyed** [comment]
https://github.com/Unicon/cas-mfa/commit/62ca78dd56211a88a9d25e46dbba7f52afa67c6c

**Comment by mmoayyed** [comment]
@jtgasper3 tagged
