### ISSUE TITLE
Current RC2 snapshot fails to deploy

### ISSUE THREAD

**Issue by dima767** [Unicon/cas-mfa#107]
cas-mfa enabled Maven war overlay with the dependency on `1.0.0-RC2-SNAPSHOT` fails to deploy with the following exception:

```java
...
2015-06-05 11:11:08,553 ERROR [org.springframework.web.servlet.DispatcherServlet] - <Context initialization failed>
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'principalAttributeMfaRequestResolver' defined in ServletContext resource [/WEB-INF/cas-servlet-override-context.xml]: Cannot resolve reference to bean 'registeredServiceMfaRoleProcessor' while setting bean property 'mfaRoleProcessor'; nested exception is org.springframework.beans.factory.NoSuchBeanDefinitionException: No bean named 'registeredServiceMfaRoleProcessor' is defined

...
```

**Comment by jtgasper3** [comment]
Hmmm, I hate Spring's context separation/hierarchy...

It's here https://github.com/Unicon/cas-mfa/blob/master/cas-mfa-web/src/main/webapp/WEB-INF/spring-configuration/mfaArgumentExtractorsConfiguration.xml#L64, and worked fine when I linked in in my override in the mfa-duo-two-factor-servlet.xml for a client. 

I'll see what needs to happen to make it happy for all. If you have any thoughts, do share.

**Comment by dima767** [comment]
OK, false alarm. Got to the cause - the thing is that I have a locally modified `mfaArgumentExtractorsConfiguration.xml` with added google extractor and obviously it's overridden the new one. Agrrrr. Oh, the joy of Maven overlays... NOT ;-)

OK, closing it. Sorry for the false alarm.
