### ISSUE TITLE
patternCache field is not being used

### ISSUE THREAD

**Issue by dima767** [Unicon/cas-mfa#110]
Seems that the `patternCache` is a "dead code" and not being used for lazily caching compiled regex Pattern instances: https://github.com/Unicon/cas-mfa/blob/master/cas-mfa-java/src/main/java/net/unicon/cas/mfa/authentication/DefaultRegisteredServiceMfaRoleProcessorImpl.java#L68

https://github.com/Unicon/cas-mfa/blob/master/cas-mfa-java/src/main/java/net/unicon/cas/mfa/authentication/DefaultRegisteredServiceMfaRoleProcessorImpl.java#L191

**Comment by jtgasper3** [comment]
Why yes, yes it is. Can't believe I forget to add the compiled regex pattern to the cache.

**Comment by dima767** [comment]
Wanna make sure you do it in the thread-safe manner e.g. use a short `synchronized` block with a mutex monitor object instance, etc.

**Comment by jtgasper3** [comment]
Please remind me... Did I need to sync reads or just the update?

**Comment by jtgasper3** [comment]
Never mind. We don't want a dirty read, so I synced both, which is fine they are a call away from each other.

**Comment by jtgasper3** [comment]
Please take a look at https://github.com/Unicon/cas-mfa/pull/111. Let me know if I'm missing something.

**Comment by dima767** [comment]
Looks good

**Comment by mmoayyed** [comment]
This is fine. You may also want to make sure you're using a ConcurrentHashMap for the cache, just to be safe. You dont actually need the ordering of a LinkedHashMap, right?

**Comment by jtgasper3** [comment]
Not any more... You are right... Let me make that change.

**Comment by mmoayyed** [comment]
via #111
