### ISSUE TITLE
CAS-MFA/Duo: Only "Failing Closed"

### ISSUE THREAD

**Issue by bafbl** [Unicon/cas-mfa#119]
Our campus recently had network-connectivity problems to Duo's servers this morning. Unfortunately, our Duo'ified CAS system required Duo during this time so people could not log in. 

In general, we would like to achieve "Fail-Open" operation, ideally reflecting in SAML data that Duo was not done. Someday, we might also take advantage of per-user and/or per-application controls to identify Fail-Closed preferences for our highest-security situations. But for now, we don't want Duo/Internet problems to break all of our campus logins.

Achieving Fail-Open operation... Right now, CAS does not talk with Duo's servers before the browser is sent to a page with the Duo iFrame. I don't know much about webflow, but I think achieving Failed-Open operation means inserting a duo-testing webflow state that can drive the browser to the Duo-iFrame page when Duo is working or back to the application with an ST if it is not.

What do you think? Is it important to your existing or potential deployments that CAS work even when Duo's servers are done (a generally rare event) or when there are hiccups in Internet access?

**Comment by mmoayyed** [comment]
At this point, this is not possible because we have no way to determine whether Duo is "up" or not. The integration between Duo and CAS is purely through a Web SDK that is JS-based, and we don't make any connections to the Duo Servers up front. We could try to ping their server when CAS comes up, but I don't think we should fail-open at all from a framework perspective. The requirement for an application is to go through MFA with Duo. You dictate that requirement. Not the framework. So, you can simply return that requirement off on a per-app basis, Duo will never be contacted, and apps will note that Duo was not done. That's the best solution we have. Anything else is way too complicated or out of scope. This is not a decision that CAS should make for you.

**Comment by mmoayyed** [comment]
@dima767 found this: https://www.duosecurity.com/docs/authapi

**Comment by bafbl** [comment]
This is letting the perfect be the enemy of the good. 

First, per-app integration is infeasible. We went down that route and only integrated Duo into some high-security applications; this was slow and left countless, smaller gaps. We concluded that our central-auth integration needs to implement a decent, default security requirement *PerUser.* Then, once all the small gaps are covered by this and the high-security requirements are (probably) 90+% met, we may choose to invest the time to write advanced checks in those few apps with higher security requirements.

For us, the default meaning of "duo required" needs to be Fail-Open:
1. Our Internet access is reliable with some number of 9s. Duo-Cloud is also reliable with some number of 9s. As many of us found out last week, that is not 100%.
1. As mentioned above, we have chosen "require" duo logins of a growing a list of users: duo is "required" for All Apps accessed by certain users. This is to cover all our web apps (low, medium and high security) in one, big step.
1. During Internet/Duo downtime, we'd rather risk the chance that a phished credential will work than to have thousands and thousands of users locked out of all their apps.

This is not unusual:
1. The MFA consortium discusses it as an option: https://wiki.cohortium.internet2.edu/confluence/display/mfacohortium/When+the+Duo+Service+Goes+Down
1. Many Duo integrations have a Fail Open option
1. Duo has a ping API call (maybe) designed for these decisions
1. Users of other CAS-Duo integrations are asking for this: https://github.com/epierce/cas-server-extension-duo/issues/2
1. The Internet2 Net+ presentation about duo (slide 32) mentions this as an option: http://www.internet2.edu/presentations/spring13/20130422-st_sauver-multifactor.pdf

Anyway, CAS should be able to implement the Normal case(s) and then either have configuration options for the abnormal ones or provide the data for Apps to implement their needs. I think Fail-Open should be an available meaning of "requiring" mfa.

We'll press Duo to see if the javascript around the duo iframe can offer a fail-open open like many of Duo's other integrations. However, I (obviously) think it is a good idea for CAS to (be able to) invoke a duo-ping API call before sending the user to duo's panel.

**Comment by mmoayyed** [comment]
Excellent. Thank you for the description. Now that I have an idea about what you intend to accomplish, this makes sense. We can certainly add this. Possibly after the v1 GA comes out.

**Comment by jtgasper3** [comment]
So a follow-up question to all... Assuming Duo was not available when the user needed MFA the initial time, should the bypass happen for the rest of the session, or should the MFA/Duo availability check happen again the next time the by-passed user request another ST within the same SSO session?

The former would be a relatively simple change to the Duo webflow, the latter would be much more complex.

**Comment by mmoayyed** [comment]
The bypass should activate anytime CAS deems necessary to contact duo. So on that initial call and perhaps renew=true calls to CAS. If you already have an MFA session, there is no need to check for the bypass when the app requests MFA.

**Comment by jtgasper3** [comment]
Not quite the angle I'm asking about, so let me try this scenario:

There are 3 client apps (A, B, C) with B and C requiring Duo.

1. User hits client app A, CAS makes them authenticate with standard username/password and is sent back to client app A.
1. User hits client app B, but Duo is not available, so the person's Duo check is bypassed and the user gets sent to app B. (Is the TGT an MFA elevated TGT or still a standard TGT?)
1. User hits client app C, and Duo *is* available. Is the user challenged for Duo MFA? They were already approved into a Duo approved app, but they didn't actually do Duo?

My thinking is that in a perfect world, Step 2 would not marked the TGT as MFA approved, so at Step 3 the user would see the Duo challenge.

However, Duo being unavailable is an edge case that should not happen very often, so the attack window with Duo being down is pretty small. So modifying the Duo workflow to exit with `mfaSuccess` on Duo bypass would be trivial, but they'd be MFA approved for the rest of their TGT session (or renew=true). In this case Step 3 would allow the user in even though they haven't done Duo and Duo is available.

**Comment by mmoayyed** [comment]
In your 2nd step, CAS has in fact not elevated the TGT and the sso session. It does and should not claim MFA is satisfied, and because of that, the app doesn't know or see it either. Because of this, when you hit app C, the user is asked for MFA. The fact that user logged into the app does not mean Duo was actually granted, because in this case that option is turned on. 

This will be a problem for poorly implemented apps that assume the only way one can login is via CAS+Duo. 

As far as placement of mfaSuccess, I agree. Implementation will not be trivial. We may need to define a new result that describes mfaSuccessButNotReallyBeCareful.

**Comment by mapgrady** [comment]
> On Sep 1, 2015, at 8:34 PM, Misagh Moayyed <notifications@github.com> wrote:
> 
> In your 2nd step, CAS has in fact not elevated the TGT and the sso session. It does and should not claim MFA is satisfied, and because of that, the app doesn't know or see it either. Because of this, when you hit app C, the user is asked for MFA. The fact that user logged into the app does not mean Duo was actually granted, because in this case that option is turned on.
> 
> This will be a problem for poorly implemented apps that assume the only way one can login is via CAS+Duo.
> 
> As far as placement of mfaSuccess, I agree. Implementation will not be trivial. We may need to define a new result that describes mfaSuccessButNotReallyBeCareful.
> 

Or mfaFailedOpen or mfaSuccessFailedOpen ?

> —
> Reply to this email directly or view it on GitHub <https://github.com/Unicon/cas-mfa/issues/119#issuecomment-136911042>.
> 


--
Michael A. Grady
IAM Architect, Unicon, Inc.

**Comment by bafbl** [comment]
I'm not following all the details here. I'll study it more.

In the meantime, here is an approach to think about: We have per-user and per-service settings for when MFA/Duo is required. These settings are considered for each login request and then compared against the current TGT/Session.

I think we would be happy if a Duo-ping was done during that computation of whether Duo is required. In other words, something like this:

```java
... look at current user and requested service ...
boolean mfaIsRequired = ...
boolean duoIsAvailable = DuoUtils.duoApiIsResponding();

if ( mfaIsRequired && !duoIsAvailable )
{
  log.warn("Reverting to single-factor because duo is not available");
  mfaIsRequired = false;
}

... continue processing request ...
```

I think this would keep all the ticket-bookkeeping and SAML information accurate, perform a Duo check before issuing STs when Duo returns, handle all the renew possibilities, etc.

Might something like this work?

**Comment by mmoayyed** [comment]
This is now handled directly in cas.
