### ISSUE TITLE
messages_en.properties isn't copied into the WAR

### ISSUE THREAD

**Issue by milesgentry** [Unicon/cas-mfa#131]
We're performing a pretty standard integration with our CAS and noticed that the messages_en.properties isn't rolled into the WAR file with the rest of the project files.  Would it be possible to roll the message_en.properties file into the WAR, replacing or appending the one included by CAS itself?
[pom.xml.txt](https://github.com/Unicon/cas-mfa/files/64447/pom.xml.txt)

**Comment by mmoayyed** [comment]
Checked. While this is a legit issue, it is expected that adopters modify the messages_en file themselves since most overlays would want to customize those messages. When they do, MFA-related messages must also be copied over to the same file. There is no way we could automate this at this point.
