### ISSUE TITLE
master fails to build with checkstyle failures

### ISSUE THREAD

**Issue by dbhankins** [Unicon/cas-mfa#134]
When attempting to perform the steps on the wiki's "Getting Started" page, the master branch fails to build due to the following checkstyle failures:

[INFO] Starting audit...
/home/daniel/IdeaProjects/cas-mfa/cas-mfa-java/src/main/java/net/unicon/cas/mfa/web/support/DefaultMultiFactorAuthenticationSupportingWebApplicationService.java:115:5: Missing a Javadoc comment.
/home/daniel/IdeaProjects/cas-mfa/cas-mfa-java/src/main/java/net/unicon/cas/mfa/web/support/DefaultMultiFactorAuthenticationSupportingWebApplicationService.java:121:123: ':' should be on a new line.
/home/daniel/IdeaProjects/cas-mfa/cas-mfa-java/src/main/java/net/unicon/cas/mfa/web/flow/AbstractMultiFactorAuthenticationViaFormAction.java:22:8: Unused import - org.jasig.cas.ticket.TicketException.
/home/daniel/IdeaProjects/cas-mfa/cas-mfa-java/src/main/java/net/unicon/cas/mfa/web/flow/AbstractMultiFactorAuthenticationViaFormAction.java:261:90: Expected @throws tag for 'Exception'.
/home/daniel/IdeaProjects/cas-mfa/cas-mfa-java/src/main/java/net/unicon/cas/mfa/web/flow/TerminatingMultiFactorAuthenticationViaFormAction.java:11:8: Unused import - org.jasig.cas.ticket.TicketException.
/home/daniel/IdeaProjects/cas-mfa/cas-mfa-java/src/main/java/net/unicon/cas/mfa/web/flow/TerminatingMultiFactorAuthenticationViaFormAction.java:68:70: Expected @throws tag for 'Exception'.
/home/daniel/IdeaProjects/cas-mfa/cas-mfa-java/src/main/java/net/unicon/cas/addons/serviceregistry/RegisteredServiceWithAttributes.java:7: First sentence should end with a period.
/home/daniel/IdeaProjects/cas-mfa/cas-mfa-java/src/main/java/net/unicon/cas/addons/serviceregistry/RegisteredServiceWithAttributes.java:15:5: Missing a Javadoc comment.
/home/daniel/IdeaProjects/cas-mfa/cas-mfa-java/src/main/java/net/unicon/cas/addons/serviceregistry/RegisteredServiceWithAttributesImpl.java:8: First sentence should end with a period.
/home/daniel/IdeaProjects/cas-mfa/cas-mfa-java/src/main/java/net/unicon/cas/addons/authentication/DefaultAuthenticationSupport.java:22:5: Missing a Javadoc comment.
/home/daniel/IdeaProjects/cas-mfa/cas-mfa-java/src/main/java/net/unicon/cas/addons/authentication/DefaultAuthenticationSupport.java:29: Line is longer than 140 characters (found 146).
/home/daniel/IdeaProjects/cas-mfa/cas-mfa-java/src/main/java/net/unicon/cas/addons/authentication/AuthenticationSupport.java:21: First sentence should end with a period.
/home/daniel/IdeaProjects/cas-mfa/cas-mfa-java/src/main/java/net/unicon/cas/addons/authentication/AuthenticationSupport.java:27:80: Expected @throws tag for 'RuntimeException'.
/home/daniel/IdeaProjects/cas-mfa/cas-mfa-java/src/main/java/net/unicon/cas/addons/authentication/AuthenticationSupport.java:29: First sentence should end with a period.
/home/daniel/IdeaProjects/cas-mfa/cas-mfa-java/src/main/java/net/unicon/cas/addons/authentication/AuthenticationSupport.java:35:83: Expected @throws tag for 'RuntimeException'.
/home/daniel/IdeaProjects/cas-mfa/cas-mfa-java/src/main/java/net/unicon/cas/addons/authentication/AuthenticationSupport.java:37: First sentence should end with a period.
/home/daniel/IdeaProjects/cas-mfa/cas-mfa-java/src/main/java/net/unicon/cas/addons/authentication/AuthenticationSupport.java:40: Line is longer than 140 characters (found 143).
/home/daniel/IdeaProjects/cas-mfa/cas-mfa-java/src/main/java/net/unicon/cas/addons/authentication/AuthenticationSupport.java:43:90: Expected @throws tag for 'RuntimeException'.
Audit done.

**Comment by mmoayyed** [comment]
master is under dev, unstable at this point. use cas36 instead.
