### ISSUE TITLE
Consider dropping maintenance

### ISSUE THREAD

**Issue by dima767** [Unicon/cas-mfa#140]
Consider dropping support and maintenance of this library and solely focus on upcoming CAS v5 full-blown, native mfa support.

**Comment by wvuboyer** [comment]
DUO at this time recommends this library on their CAS application page. Dropping support before cas 5 is delivered leaves users stuck between a less than fully functioning module, and a not-yet released cas product.

https://duo.com/docs/cas

**Comment by dima767** [comment]
Note, this issue is not suggesting to drop support right this moment, but to do so once CAS 5.0 is generally available. 

Best,
D.

**Comment by vanadaar** [comment]
OK Thanks, just wanted to make sure it was taken into consideration.

**Comment by dima767** [comment]
But I do not believe that this module will be actively developed in any case from this point on. Only "maintenance" mode until CAS 5 is available.

**Comment by vanadaar** [comment]
My concern is that in issue 137 it's hinted that maintenance mode is also pretty much ended as of this time.

**Comment by mmoayyed** [comment]
Not it's not ended. We'd be happy to accept patches, cut releases and respond to issues. We just wont actively develop this further to include more features and enhancements. As Dima says, this is purely in maintenance mode with the expectation that the community participates in the development, or that we are provided adequate funding and support to take this further.
