### ISSUE TITLE
Returning casServiceFailureView after Successful ST Validation

### ISSUE THREAD

**Issue by evergreen-netservices** [Unicon/cas-mfa#55]
With the MFA extension, CAS returns the casServiceFailureView view to clients calling serviceValidate, despite the fact that the actual validation is successful. This problem began when a new service was added that has very long service URL. The symptom only presents on the second or subsequent ST validation after TGT creation. Reverting back to a non-MFA CAS demonstrates that the problem only occurs in MFA CAS. The symptoms do not occur only on requests with these very long service URL, rather, the service with very long URL puts CAS in a state where this happens with all services and a CAS restart is required to correct it. Additionally, a single instance of the very long URL will not necessarily trigger the problem. We added a few logger.debug lines to MultiFactorServiceValidateController.java and started getting a bit more info about where the problem was occurring:
2014-01-23 11:10:26,703 DEBUG [net.unicon.cas.mfa.web.MultiFactorServiceValidateController] - <ServiceTicket [ST-117-DLSkRVYvyer9tiTuEvqt-cas01.example.org] does not satisfy validation specification.>
2014-01-23 11:10:26,703 DEBUG [net.unicon.cas.mfa.web.MultiFactorServiceValidateController] - <convertedDescription is ticket ''{0}'' not recognizedand code is INVALID_TICKET>
From MultiFactorServiceValidateController.java:
                if (!validationSpecification.isSatisfiedBy(assertion)) {
                    logger.debug("ServiceTicket [" + serviceTicketId + "] does not satisfy validation specification.");
                    return generateErrorView("INVALID_TICKET", "INVALID_TICKET_SPEC", null);

I may be able to correct or provide more info but I need a little assistance in where to start looking.

**Comment by JohnPfeifer** [comment]
We are seeing the same issue with the M3 build where the CAS logs show a successful ST validation but the service is receiving a  failure response with a "ticket ''{0}'' not recognized" message.

We are preparing to upgrade to the M6 build.  Has this issue been resolved that version?

**Comment by keyith** [comment]
I haven't heard that this has been fixed, and it wasn't fixed in the "almost-M3" version I last tried. This began happening for us when we added a service (OCLC's EZProxy) that often uses renew=true; prior to that we hadn't see this issue. JohnPfeifer, can you add any details about when this happens, specifically with regard to requests where renew=true (my best guess/current suspicion)?

**Comment by mmoayyed** [comment]
Yes, details would be very helpful in figuring this out. Particularly, trace calls from the app to the CAS server with renew=true would be helpful. We have not been able to successfully duplicate this problem, but hopefully with more data we'll review more thoroughly.

**Comment by JohnPfeifer** [comment]
It does not seem to be related to renew=true.  There are only one or two services which use the renew flag and the are not reporting any problems.

Reproducibility is the bane of this problem.  It occurs irregularly on some services that are in their period of peak usage.  I have been unable to reproduce it in my dev or qa environments.

I should also note that the services in question are not doing MFA.

> On Feb 2, 2015, at 12:01 PM, Misagh Moayyed <notifications@github.com> wrote:
> 
> Yes, details would be very helpful in figuring this out. Particularly, trace calls from the app to the CAS server with renew=true would be helpful. We have not been able to successfully duplicate this problem, but hopefully with more data we'll review more thoroughly.
> 
> —
> Reply to this email directly or view it on GitHub.
> 


//
John Pfeifer
Division of Information Technology
University of Maryland, College Park

**Comment by mmoayyed** [comment]
Good to know that it's not MFA-request related.  I think @keyith mentioned that he was not able to duplicate this with a vanilla CAS server. It *may* be some place in the MFA code that tries to handle non-mfa functionality perhaps. I'll run a few more tests with the latest M6 or later with some load and see if I can make sense out of this. If you can capture tomcat/server access requests logs that correlate with the issue, it would help.

**Comment by JohnPfeifer** [comment]
After much ado, we may have solved it.  We were never able to reproduce the problem in our qa environment but, after a week of running the patched code in production, we have not seen this error again.

The issue is with how the validationSpecificationClass is handled differently in this code v/s the stock ServiceValidateController class.  In the JASIG code, a new instance is created by each call to getCommandClass() where, as in the Unicon code, there is a single instance that gets reused.

I believe that this leads to a race condition when you have a mix of mfa and non-mfa requests happening at the same instant (which would explain the challenge in reproducing the problem).

Below is the patch that I wrote:

```
46a47
> import java.lang.reflect.Constructor;
100,101c101
<     private MultiFactorAuthenticationProtocolValidationSpecification validationSpecificationClass
<             = new MultiFactorAuthenticationProtocolValidationSpecification(false);
---
>     private Class<?> validationSpecificationClass = MultiFactorAuthenticationProtocolValidationSpecification.class;
289c289,290
<             return this.validationSpecificationClass;
---
>             Constructor<?> ctor = this.validationSpecificationClass.getConstructor(boolean.class);
>             return (MultiFactorAuthenticationProtocolValidationSpecification) ctor.newInstance(false);
335c336
<         this.validationSpecificationClass = validationSpecificationClass;
---
>         this.validationSpecificationClass = validationSpecificationClass.getClass();
```

Alternately, you could declare MultiFactorAuthenticationProtocolValidationSpecification to be Cloneable and then getCommandClass() could clone the instance.

**Comment by mmoayyed** [comment]
@JohnPfeifer thanks very much for the patch. I'll get to it tomorrow to merge the change into the mfa codebase. [or if you'd rather submit a PR, I'd be happy to merge that as well]

**Comment by mmoayyed** [comment]
@JohnPfeifer before I apply a patch, could you test one more time with scope set to prototype for the following beans:

```
    <bean id="mfaValidationWithoutProxySupportSpec"
          class="net.unicon.cas.mfa.MultiFactorAuthenticationProtocolValidationSpecification"
          c:validateProxyAuthenticationRequests="false"
          scope="prototype"/>

    <bean id="mfaValidationWithProxySupportSpec"
          class="net.unicon.cas.mfa.MultiFactorAuthenticationProtocolValidationSpecification"
          c:validateProxyAuthenticationRequests="true"
          scope="prototype"/>
```

**Comment by keyith** [comment]
Are you asking to test the straight M6 code or the modified code with that scope set for those two beans?

**Comment by mmoayyed** [comment]
The M6 code.

**Comment by mmoayyed** [comment]
Actually, to clarify, the M6 code with the two beans modified for their scope.

**Comment by keyith** [comment]
That was the easy part; integrating our overlay with the M6 code is proving more difficult. Is there any reason I can't change the scope of those two beans to "prototype" in our M0 code?

Also, I've been thinking about this a lot lately, and want to point out that I've been able to repro the issue on the server serving EZProxy without any MFA requests, while the server serving both MFA and non-MFA requests but not EZProxy hasn't had the issue. I think the logic behind creating a new instance vs. a single instance still stands, but I wanted to call that out.

**Comment by mmoayyed** [comment]
Sure, M0 would be fine too.

**Comment by keyith** [comment]
I made the scope change to those two beans in our existing M0 code and got permission to deploy it to our CAS server dedicated to EZProxy yesterday at 10am. In past attempts, the failures began occurring within 2 hours of deployment, but today I am happy to say that we haven't encountered the issue after 24 hours! So far, so good...

Current plans call for running it for the rest of this week, and if we still haven't encountered the issue, we'll deploy it to the main production CAS server next Sunday morning.

**Comment by mmoayyed** [comment]
Excellent news. I'll wait to hear back from you, and if the change still holds, we'll modify the code to include that. Thanks again.

**Comment by dima767** [comment]
And cut RC1, perhaps ;-)

**Comment by mmoayyed** [comment]
I made a few changes to fix the renew behavior.
